export const i18n = {
  en: {
    chooseLanguage: 'Choose Language',
    tapHint: 'Tap anywhere to check zoning',
    searchPlaceholder: 'Search Kigali...',
    download: 'Download PDF',
    share: 'Share',
    askPlaceholder: 'Ask about zoning, permits...',
    loading: 'Checking zoning...',
    step1Title: 'Tap the Map',
    step1Desc: 'Select any location in Kigali',
    step2Title: 'Ask Questions',
    step2Desc: 'Get instant zoning guidance',
    step3Title: 'Download Report',
    step3Desc: 'Save official documentation',
    enterApp: 'Start',
    welcome: (zone) => `**Welcome to ZoneAgent**

This location is classified as:
**${zone}**

What You Can Ask:

• What types of buildings are permitted here?
• What are the height and setback requirements?
• What permits do I need to build?
• Is this zone suitable for commercial use?

Type your question below.`,
    outsideKigali: 'This location is outside Kigali zoning coverage.\n\nPlease select a location within Kigali City.',
    error: 'Something went wrong. Please try again.',
    noZoning: 'No zoning data available for this location.',
    reportTitle: 'ZONING COMPLIANCE REPORT',
    generatedBy: 'Generated by ZoneAgent',
    locationLabel: 'Location',
    dateLabel: 'Date',
    questionLabel: 'Question',
    analysisLabel: 'Analysis',
    contactLabel: 'Official Contacts',
    disclaimer: 'This report is for informational purposes only. Verify with City of Kigali authorities.',
  },
  rw: {
    chooseLanguage: 'Hitamo Ururimi',
    tapHint: 'Kanda ahantu kureba imiyoborere',
    searchPlaceholder: 'Shakisha muri Kigali...',
    download: 'Kuramo PDF',
    share: 'Sangiza',
    askPlaceholder: 'Baza ku miyoborere...',
    loading: 'Kureba imiyoborere...',
    step1Title: 'Kanda Ikarita',
    step1Desc: 'Hitamo aho hantu muri Kigali',
    step2Title: 'Baza Ibibazo',
    step2Desc: 'Kubona amakuru vuba',
    step3Title: 'Kuramo Raporo',
    step3Desc: 'Kubika inyandiko',
    enterApp: 'Tangira',
    welcome: (zone) => `**Murakaza neza kuri ZoneAgent**

Aha hantu hafite imiyoborere:
**${zone}**

Ibyo Ushobora Kubaza:

• Ni ubuhe bwubatsi bwemewe aha?
• Ni izihe ntera n'imipaka isabwa?
• Ni uruhe ruhushya nkeneye kubaka?
• Ese hashobora gukoreshwa mu bucuruzi?

Andika ikibazo cyawe hano.`,
    outsideKigali: "Aha hantu ni inyuma y'imiyoborere ya Kigali.",
    error: 'Habaye ikibazo. Ongera ugerageze.',
    noZoning: "Nta makuru y'imiyoborere.",
    reportTitle: "RAPORO Y'IMIYOBORERE",
    generatedBy: 'Yakozwe na ZoneAgent',
    locationLabel: 'Aho hantu',
    dateLabel: 'Itariki',
    questionLabel: 'Ikibazo',
    analysisLabel: 'Isesengura',
    contactLabel: 'Aho Wakwiyambaza',
    disclaimer: "Emeza amakuru yose n'ubuyobozi bw'Umujyi wa Kigali.",
  },
  fr: {
    chooseLanguage: 'Choisir la Langue',
    tapHint: 'Appuyez pour vérifier le zonage',
    searchPlaceholder: 'Rechercher à Kigali...',
    download: 'Télécharger PDF',
    share: 'Partager',
    askPlaceholder: 'Questions sur le zonage...',
    loading: 'Vérification...',
    step1Title: 'Appuyez sur la Carte',
    step1Desc: 'Sélectionnez un lieu à Kigali',
    step2Title: 'Posez des Questions',
    step2Desc: 'Conseils instantanés',
    step3Title: 'Téléchargez',
    step3Desc: 'Sauvegardez le rapport',
    enterApp: 'Commencer',
    welcome: (zone) => `**Bienvenue sur ZoneAgent**

Cette zone est classée:
**${zone}**

Questions Possibles:

• Quels bâtiments sont autorisés?
• Exigences de hauteur?
• Permis nécessaires?
• Usage commercial possible?

Tapez votre question.`,
    outsideKigali: 'Hors zone de Kigali.',
    error: 'Erreur. Réessayez.',
    noZoning: 'Pas de données.',
    reportTitle: 'RAPPORT DE ZONAGE',
    generatedBy: 'Généré par ZoneAgent',
    locationLabel: 'Emplacement',
    dateLabel: 'Date',
    questionLabel: 'Question',
    analysisLabel: 'Analyse',
    contactLabel: 'Contacts',
    disclaimer: 'Vérifiez auprès de la Ville de Kigali.',
  },
}

export function t(lang, key, ...args) {
  const val = (i18n[lang] || i18n.en)[key] ?? i18n.en[key] ?? key
  return typeof val === 'function' ? val(...args) : val
}
