export const ZONE_COLORS = {
  'A1-Agriculture zone': '#90EE90',
  'C1-Mixed use zone': '#FFB6C1',
  'C3-City commercial zone': '#CD5626',
  'I1-Light industrial zone': '#DDA0DD',
  'I2-General industrial zone': '#9370DB',
  'I3-Mining/ Extraction/Quarry': '#8B4513',
  'P1-Parks and open spaces zone': '#32CD32',
  'P2-Sport and Eco tourism zone': '#00FA9A',
  'P3B-Forest zone': '#006400',
  'P3C-Steep slopes (> 30%) zone': '#2E8B57',
  'PA-Public Administration zone': '#87CEEB',
  'PF1-Education and research facilities': '#4169E1',
  'PF2-Health facilities': '#0000FF',
  'PF3-Religious facilities': '#191970',
  'PF4-Cultural/ memorial sites': '#6495ED',
  'PF5-Cemetery/ crematoria': '#B0C4DE',
  'R1-Low density residential zone': '#FFFFE0',
  'R1A-Low density residential densification zone': '#FFFACD',
  'R1B-Rural residential zone': '#F0E68C',
  'R2-Medium density residential - Improvement zone': '#F59E0B',
  'R3-Medium density residential - Expansion zone': '#FF7F50',
  'R4-High density residential zone': '#FF6347',
  'T-Transportation zone': '#A9A9A9',
  'U-Utility zone': '#D3D3D3',
  'W2 - Rehabilitation': '#98FB98',
  'W3 - Sustainable Exploitation': '#90EE90',
  'W4 - Conservation': '#8FBC8F',
  'W5 - Recreational': '#87CEEB',
  'WR-Waterbody zone': '#87CEEB',
}

export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://cok-development-assistant.onrender.com/api'
